sudo: required
if: "branch = master"

jobs:
  include:
    - stage: test
      services:
        - docker
      before_script:
        - "docker build -t hugovp/react-test -f ./frontend/dev.dockerfile ./frontend"
      script:
        - "docker run hugovp/react-test npm run test -- --coverage"
      after_success:
        - "docker build -t hugovp/burger-builder-nginx ./nginx"
        - "docker build -t hugovp/burger-builder-web ./web"
        - "docker build -t hugovp/burger-builder-frontend ./frontend"
        - "docker build -t hugovp/burger-builder-backend ./backend"

        # Log in to the Docker CLI
        - "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_ID\" --password-stdin"

        # Take the images and push then to Docker Hub
        - "docker push hugovp/burger-builder-frontend"
        - "docker push hugovp/burger-builder-nginx"
        - "docker push hugovp/burger-builder-web"
        - "docker push hugovp/burger-builder-backend"

    - stage: frontend
      script: skip
      before_deploy:
        - "cd ./frontend"
      deploy: &heroku
        provider: heroku
        api_key: $HEROKU_API_KEY
        app: $HEROKU_FRONTEND_APP_NAME
        on:
          repo: HugoVP/burger-builder-react-laravel
          branch: master
    
    - stage: backend
      script: skip
      before_deploy:
        - "cd ./backend"
      deploy:
        <<: *heroku
        app: $HEROKU_BACKEND_APP_NAME
        run:
          - "php artisan route:cache"
          - "php artisan config:cache"
          - "php artisan migrate --force"
