version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: dev.dockerfile
      context: ./nginx
    ports:
      - 3001:80
  frontend:
    restart: on-failure
    build:
      dockerfile: dev.dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
  backend:
    restart: on-failure
    build:
      dockerfile: dev.dockerfile
      context: ./backend
    command: |
      sh -c
        "chmod +x wait-for.sh;
        ./wait-for.sh database:3306 -- sh -c \
          'php artisan migrate;
          php artisan serve --host=0.0.0.0 --port=8000;'"
    volumes:
      - /var/www/vendor
      - ./backend:/var/www
    depends_on:
      - database
  database:
    restart: on-failure
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    ports:
      - 33061:3306
volumes:
  dbdata:
