version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: dev.dockerfile
      context: ./nginx
    ports:
      - 3210:80
  frontend:
    restart: on-failure
    build:
      dockerfile: dev.dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - 3001:3000
  backend:
    restart: on-failure
    build:
      dockerfile: dev.dockerfile
      context: ./backend
    command: sh -c 'chmod +x wait-for.sh && ./wait-for.sh ${DB_HOST}:${DB_PORT} -- php artisan migrate && php artisan serve --host=0.0.0.0 --port=${BACKEND_PORT}'
    volumes:
      - /var/www/vendor
      - ./backend:/var/www
    env_file: ./.env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - database
  database:
    restart: on-failure
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - ./database/dbdata:/var/lib/mysql
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 33061:3306
volumes:
  dbdata:
