version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: dev.dockerfile
      context: ./nginx
    ports:
      - 8080:80
    command: |
      sh -c 
        "chmod +x wait-for.sh;
        ./wait-for.sh frontend:3000 --
          ./wait-for.sh web:9000 --
            nginx -g \"daemon off;\""
  frontend:
    restart: on-failure
    depends_on: 
      - nginx
    build:
      dockerfile: dev.dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    command: npm run start
  web:
    restart: on-failure
    depends_on: 
      - nginx
    build: 
      context: ./web
    volumes: 
      - ./backend:/var/www
  backend:
    restart: on-failure
    depends_on:
      - web
      - database
    build:
      dockerfile: dev.dockerfile
      context: ./backend
    env_file: ./backend/.env
    volumes: 
      - /var/www/vendor
      - ./backend:/var/www
      - ./web:/usr/local/etc/php-fpm.d/zz-log.conf
    command: |
      sh -c
        "chmod +x wait-for.sh;
        ./wait-for.sh database:3306 --
          php artisan config:cache;
          php artisan route:cache;
          php artisan migrate --force;
          php-fpm;"    
  database:
    restart: on-failure
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./database/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    ports:
      - 33061:3306
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
volumes:
  dbdata:
