version: "3"
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - 8080:80
  frontend:
    build:
      context: ./frontend
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env.production
    command: |
      sh -c
        "php artisan config:cache;
        php artisan migrate --force;
        php artisan serve --host=0.0.0.0 --port=8000;"